-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.alocacao
(
    id_alocacao integer NOT NULL,
    id_funcionario integer NOT NULL,
    dt_competencia date NOT NULL,
    horas_alocadas numeric(10, 2) NOT NULL,
    CONSTRAINT alocacao_pkey PRIMARY KEY (id_alocacao)
);

CREATE TABLE IF NOT EXISTS public.cargos
(
    id_cargo integer NOT NULL,
    nome_cargo character varying(255) COLLATE pg_catalog."default" NOT NULL,
    senioridade character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT cargos_pkey PRIMARY KEY (id_cargo)
);

CREATE TABLE IF NOT EXISTS public.funcionarios
(
    id_funcionario integer NOT NULL,
    nome character varying(255) COLLATE pg_catalog."default" NOT NULL,
    dt_admissao date NOT NULL,
    dt_demissao date,
    salario numeric(10, 2),
    id_cargo integer NOT NULL,
    id_projeto integer NOT NULL,
    CONSTRAINT funcionarios_pkey PRIMARY KEY (id_funcionario)
);

CREATE TABLE IF NOT EXISTS public.projetos
(
    id_projeto integer NOT NULL,
    nome_projeto character varying(255) COLLATE pg_catalog."default" NOT NULL,
    dt_criacao date NOT NULL,
    dt_encerramento date,
    CONSTRAINT projetos_pkey PRIMARY KEY (id_projeto)
);

ALTER TABLE IF EXISTS public.alocacao
    ADD CONSTRAINT alocacao_funcionario_fkey FOREIGN KEY (id_funcionario)
    REFERENCES public.funcionarios (id_funcionario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.funcionarios
    ADD CONSTRAINT funcionarios_cargos_fkey FOREIGN KEY (id_cargo)
    REFERENCES public.cargos (id_cargo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.funcionarios
    ADD CONSTRAINT funcionarios_projetos_fkey FOREIGN KEY (id_projeto)
    REFERENCES public.projetos (id_projeto) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;